openapi: 3.0.1
info:
  title: 猜灯谜助手
  description: 智能助手帮助用户玩猜灯谜游戏，智能助手提供谜面，判断用户的答案是否正确，并在用户需要时揭示谜底。
  version: "v1"
servers:
  - url: https://github.com/June-default/June/tree/main/riddle_assistant
paths:
  /play_riddle:
    post:
      operationId: playRiddle
      summary: 猜灯谜游戏
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/playRiddleRequest"
      responses:
        "200":
          description: 回答判断结果
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/playRiddleResponse"
      security:
        - service_http: []

components:
  schemas:
    playRiddleRequest:
      type: object
      required: [riddle_answer]
      properties:
        riddle_answer:
          type: string
          description: 用户猜测的答案

    playRiddleResponse:
      type: object
      properties:
        is_correct:
          type: boolean
          description: 用户答案是否正确
        riddle_answer:
          type: string
          description: 谜底
