openapi: 3.0.1
info:
  title: 猜灯谜助手
  description: 智能助手帮助用户玩猜灯谜游戏，提供谜面，判断用户的答案是否正确，并在用户需要时揭示谜底。
  version: "v1"
servers:
  - url: https://github.com/June-default/June/tree/main/riddle_assistant
paths:
  /riddle:
    get:
      summary: 提出猜灯谜
      responses:
        "200":
          description: 返回猜灯谜的谜面
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/riddle"
    post:
      summary: 检查答案是否正确
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/answer"
      responses:
        "200":
          description: 返回答案判断结果
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/result"
  /reveal:
    get:
      summary: 揭晓猜灯谜的谜底
      parameters:
        - name: riddle_id
          in: query
          required: true
          schema:
            type: string
          description: 猜灯谜的唯一标识符
      responses:
        "200":
          description: 返回猜灯谜的谜底
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/reveal"
components:
  schemas:
    riddle:
      type: object
      properties:
        riddle:
          type: string
          description: 猜灯谜的谜面
    answer:
      type: object
      required:
        - riddle_id
        - user_answer
      properties:
        riddle_id:
          type: string
          description: 猜灯谜的唯一标识符
        user_answer:
          type: string
          description: 用户回答的答案
    result:
      type: object
      properties:
        is_correct:
          type: boolean
          description: 回答判断结果，true表示回答正确，false表示回答错误
        reveal:
          type: string
          description: 如果用户要求揭晓，则返回猜灯谜的谜底
    reveal:
      type: object
      properties:
        reveal:
          type: string
          description: 猜灯谜的谜底
